export const checkoutPageSelectors = {
  product: ".product-item-photo",
  size: "#option-label-size-143-item-168",
  color: "#option-label-color-93-item-57",
  quantity: "#qty",
  addToCart: "#product-addtocart-button",
  cartButton: "a.action.showcart",
  proceedToCheckout: "#top-cart-btn-checkout",
  modal: "#ui-id-1",
  email: "#customer-email",
  firstName: "[name='firstname']",
  lastName: "[name='lastname']",
  streetAdress: "[name='street[0]']",
  city: "[name='city']",
  country: "[name='country_id']",
  postCode: "[name='postcode']",
  state: "[name='shippingAddress.region_id'] > div > select",
  phone: "[name='telephone']",
  nextButton: "button[data-role='opc-continue']",
  placeOrderButton: "button.action.primary.checkout",
}
